DROP TABLE MEMBER;

CREATE TABLE MEMBER(
--    ID VARCHAR2(100) NOT NULL UNIQUE,
    ID VARCHAR2(100) PRIMARY KEY -- 기본키 대표칼럼설정 (NOT NULL, UNIQUE 포함),
    , PWD VARCHAR2(100) NOT NULL
);

INSERT INTO MEMBER VALUES ('SWY', '1234');
INSERT INTO MEMBER VALUES (NULL, '1234');
INSERT INTO MEMBER VALUES('SWY', NULL);

SELECT * FROM MEMBER;